version: "3.7"

services:
  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: db_app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "5370", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5370

  celery_worker:
    build:
      context: .
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      redis:
        condition: service_healthy

  celery_beat:
    build:
      context: .
    container_name: celery_beat_app
    command: celery --app=src.tasks.celery_app:celery beat -l INFO
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  flower:
    build:
      context: .
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_started
    ports:
      - 8888:5555

  app:
    volumes:
      - ./alembic/versions:/fastapi_app/alembic/versions
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    env_file: .env 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy